language: rust
rust:
  - 1.24.0
before_install:
    - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O SDL2-2.0.7.tar.gz
    - tar -xzvf SDL2-2.0.7.tar.gz
install:
   - (cd SDL2-2.0.7 && ./configure && make && sudo make install)
script:
  - make ci